# Generated by Django 6.0.4 on 2026-05-24 07:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_plancuidado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LogAcceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(choices=[('ver_paciente', 'Ver ficha de paciente'), ('ver_metricas', 'Ver métricas'), ('agregar_nota', 'Agregar nota clínica'), ('agregar_plan', 'Agregar plan de cuidados'), ('eliminar_plan', 'Eliminar plan de cuidados'), ('marcar_alerta', 'Marcar alerta como resuelta'), ('generar_pdf', 'Generar reporte PDF'), ('registrar_paciente', 'Registrar paciente'), ('simular_metrica', 'Simular métrica')], max_length=30)),
                ('descripcion', models.TextField(blank=True)),
                ('ip', models.GenericIPAddressField(blank=True, null=True)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='core.paciente')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
