# Generated by Django 6.0.4 on 2026-05-24 19:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_logacceso'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(choices=[('medicina_general', 'Medicina General'), ('cardiologia', 'Cardiología'), ('endocrinologia', 'Endocrinología'), ('neumologia', 'Neumología'), ('medicina_interna', 'Medicina Interna'), ('otro', 'Otro')], default='medicina_general', max_length=30)),
                ('cmp', models.CharField(blank=True, max_length=20, verbose_name='Número CMP')),
                ('telefono', models.CharField(blank=True, max_length=15)),
                ('bio', models.TextField(blank=True, verbose_name='Descripción profesional')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_medico', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
