# Generated by Django 6.0.4 on 2026-04-24 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_paciente_medico_remove_metricaconfig_paciente_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metrica',
            name='estado',
        ),
        migrations.AddField(
            model_name='metrica',
            name='alerta',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metricas', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='metrica',
            name='valor',
            field=models.CharField(max_length=20),
        ),
    ]
