# Generated by Django 6.0.4 on 2026-05-24 06:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_notaclinica'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanCuidado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('medicamento', 'Medicamento'), ('metrica', 'Toma de Métrica')], max_length=20)),
                ('tipo_metrica', models.CharField(blank=True, choices=[('glucosa', 'Glucosa'), ('presion', 'Presión Arterial'), ('saturacion', 'Saturación de Oxígeno'), ('frecuencia', 'Frecuencia Cardíaca')], max_length=20, null=True)),
                ('descripcion', models.CharField(max_length=255)),
                ('hora', models.TimeField()),
                ('frecuencia', models.CharField(choices=[('diario', 'Diario'), ('semanal', 'Semanal'), ('mensual', 'Mensual')], default='diario', max_length=10)),
                ('activo', models.BooleanField(default=True)),
                ('fecha_inicio', models.DateField(auto_now_add=True)),
                ('creado_por', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planes_creados', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planes', to='core.paciente')),
            ],
            options={
                'ordering': ['hora'],
            },
        ),
    ]
