# Generated by Django 6.0.4 on 2026-06-19 06:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_perfilmedico'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='telefono',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='enfermedad',
            field=models.CharField(choices=[('diabetes_t2', 'Diabetes Tipo 2'), ('diabetes_t1', 'Diabetes Tipo 1'), ('hipertension', 'Hipertensión Arterial'), ('asma', 'Asma'), ('epoc', 'EPOC'), ('irc', 'Insuficiencia Renal Crónica'), ('icc', 'Insuficiencia Cardíaca Crónica'), ('artritis', 'Artritis Reumatoide'), ('otra', 'Otra')], max_length=100),
        ),
        migrations.CreateModel(
            name='FichaMedica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_sangre', models.CharField(blank=True, choices=[('A+', 'A+'), ('A-', 'A-'), ('B+', 'B+'), ('B-', 'B-'), ('AB+', 'AB+'), ('AB-', 'AB-'), ('O+', 'O+'), ('O-', 'O-')], max_length=3)),
                ('peso_kg', models.FloatField(blank=True, null=True)),
                ('talla_cm', models.FloatField(blank=True, null=True)),
                ('alergias', models.TextField(blank=True)),
                ('cirugias_previas', models.TextField(blank=True)),
                ('hospitalizaciones', models.TextField(blank=True)),
                ('antecedentes_familiares', models.TextField(blank=True)),
                ('historia_enfermedad', models.TextField(blank=True)),
                ('contacto_emergencia_nombre', models.CharField(blank=True, max_length=100)),
                ('contacto_emergencia_tel', models.CharField(blank=True, max_length=15)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('paciente', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ficha', to='core.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Prescripcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=200)),
                ('dosis', models.CharField(max_length=100)),
                ('via', models.CharField(choices=[('oral', 'Oral'), ('iv', 'Intravenosa'), ('sc', 'Subcutánea'), ('im', 'Intramuscular'), ('topica', 'Tópica'), ('inhalada', 'Inhalada')], default='oral', max_length=20)),
                ('frecuencia', models.CharField(choices=[('cada_4h', 'Cada 4 horas'), ('cada_6h', 'Cada 6 horas'), ('cada_8h', 'Cada 8 horas'), ('cada_12h', 'Cada 12 horas'), ('cada_24h', 'Una vez al día'), ('segun_necesidad', 'Según necesidad')], max_length=20)),
                ('indicaciones', models.TextField(blank=True)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('activa', models.BooleanField(default=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescripciones', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescripciones', to='core.paciente')),
            ],
            options={
                'ordering': ['-fecha_inicio'],
            },
        ),
        migrations.CreateModel(
            name='UmbralPersonalizado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_metrica', models.CharField(choices=[('glucosa', 'Glucosa (mg/dL)'), ('presion_sistolica', 'Presión Sistólica (mmHg)'), ('presion_diastolica', 'Presión Diastólica (mmHg)'), ('saturacion', 'Saturación O2 (%)'), ('frecuencia', 'Frecuencia Cardíaca (lpm)')], max_length=30)),
                ('valor_min', models.FloatField(blank=True, null=True)),
                ('valor_max', models.FloatField(blank=True, null=True)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='umbrales', to='core.paciente')),
            ],
            options={
                'unique_together': {('paciente', 'tipo_metrica')},
            },
        ),
    ]
