# Generated by Django 6.0.4 on 2026-06-19 09:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_paciente_fecha_nacimiento_paciente_telefono_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('primera_vez', 'Primera vez'), ('control', 'Control rutinario'), ('seguimiento', 'Seguimiento'), ('urgencia', 'Urgencia')], default='control', max_length=20)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('realizada', 'Realizada'), ('cancelada', 'Cancelada'), ('no_asistio', 'No asistió')], default='programada', max_length=20)),
                ('fecha_hora', models.DateTimeField()),
                ('motivo', models.CharField(max_length=300)),
                ('diagnostico', models.TextField(blank=True)),
                ('indicaciones', models.TextField(blank=True)),
                ('proxima_cita', models.DateField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('medico', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultas', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='core.paciente')),
            ],
            options={
                'ordering': ['fecha_hora'],
            },
        ),
    ]
