# Generated by Django 6.0.4 on 2026-06-24 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_consulta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerta',
            name='paciente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alertas', to='core.paciente'),
        ),
        migrations.AlterField(
            model_name='logacceso',
            name='accion',
            field=models.CharField(choices=[('ver_paciente', 'Ver ficha de paciente'), ('ver_metricas', 'Ver métricas'), ('agregar_nota', 'Agregar nota clínica'), ('agregar_plan', 'Agregar plan de cuidados'), ('eliminar_plan', 'Eliminar plan de cuidados'), ('marcar_alerta', 'Marcar alerta como resuelta'), ('generar_pdf', 'Generar reporte PDF'), ('registrar_paciente', 'Registrar paciente')], max_length=30),
        ),
    ]
