# Generated by Django 6.0.4 on 2026-06-26 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_alerta_paciente_alter_logacceso_accion'),
    ]

    operations = [
        migrations.AddField(
            model_name='metrica',
            name='valor_diastolica',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
